#!/bin/sh

# $FreeBSD: tags/RELEASE_9_1_0/net/minidlna/files/minidlna.in 302141 2012-08-05 23:19:36Z dougb $
#
# PROVIDE: minidlna
# REQUIRE: LOGIN
# KEYWORD: shutdown
#

. /etc/rc.subr
. /etc/configxml.subr

name=minidlna
homefolder=`configxml_get "//$name/homefolder"`

config=${homefolder}${name}\.conf
command=/usr/local/sbin/$name
pidfile="/var/run/$name\.pid"

start_precmd="rm -f $pidfile"
stop_postcmd=$start_precmd

command_args="-P $pidfile -f $config"
extra_commands=rescan
rescan_cmd="$command -R "


run_rc_command $1